import {
  Document as DocxDocument,
  Packer,
  Paragraph,
  TextRun,
  HeadingLevel,
  AlignmentType,
  BorderStyle,
  PageBreak,
  Footer,
  Header,
  Table,
  TableRow,
  TableCell,
  ExternalHyperlink,
} from "docx";

/**
 * Konversi markdown PRD ke DOCX
 */
export async function generateDocx(
  title: string,
  markdown: string
): Promise<Buffer> {
  const children = parseMarkdownToDocxElements(markdown, title);

  const doc = new DocxDocument({
    title,
    description: "PRD generated by BuatPakeAI",
    creator: "BuatPakeAI",
    styles: {
      default: {
        document: {
          run: {
            font: "Calibri",
            size: 22,
            color: "333333",
          },
          paragraph: {
            spacing: {
              after: 120,
              line: 276,
            },
          },
        },
      },
    },
    sections: [
      {
        properties: {
          page: {
            margin: {
              top: 1440,
              right: 1440,
              bottom: 1440,
              left: 1440,
            },
          },
        },
        headers: {
          default: new Header({
            children: [
              new Paragraph({
                alignment: AlignmentType.RIGHT,
                children: [
                  new TextRun({
                    text: "BuatPakeAI — PRD Generator",
                    font: "Calibri",
                    size: 16,
                    color: "999999",
                    italics: true,
                  }),
                ],
              }),
            ],
          }),
        },
        footers: {
          default: new Footer({
            children: [
              new Paragraph({
                alignment: AlignmentType.CENTER,
                children: [
                  new TextRun({
                    text: "Dokumen ini dibuat secara otomatis oleh BuatPakeAI",
                    font: "Calibri",
                    size: 16,
                    color: "999999",
                  }),
                ],
              }),
            ],
          }),
        },
        children,
      },
    ],
  });

  const buffer = await Packer.toBuffer(doc);
  return Buffer.from(buffer);
}

function parseMarkdownToDocxElements(
  markdown: string,
  documentTitle: string
): (Paragraph | Table)[] {
  const elements: (Paragraph | Table)[] = [];

  // Title page
  elements.push(
    new Paragraph({ spacing: { before: 3000 }, children: [] }),
    new Paragraph({
      heading: HeadingLevel.TITLE,
      alignment: AlignmentType.CENTER,
      spacing: { after: 200 },
      children: [
        new TextRun({
          text: documentTitle,
          bold: true,
          size: 52,
          color: "1E40AF",
        }),
      ],
    }),
    new Paragraph({
      alignment: AlignmentType.CENTER,
      spacing: { after: 100 },
      children: [
        new TextRun({
          text: "Product Requirements Document",
          size: 28,
          color: "666666",
          italics: true,
        }),
      ],
    }),
    new Paragraph({
      alignment: AlignmentType.CENTER,
      spacing: { after: 50 },
      children: [
        new TextRun({
          text: `Dibuat: ${new Date().toLocaleDateString("id-ID", {
            year: "numeric",
            month: "long",
            day: "numeric",
          })}`,
          size: 20,
          color: "999999",
        }),
      ],
    }),
    new Paragraph({
      alignment: AlignmentType.CENTER,
      spacing: { after: 50 },
      children: [
        new TextRun({
          text: "Dibuat dengan BuatPakeAI",
          size: 18,
          color: "AAAAAA",
        }),
      ],
    }),
    new Paragraph({ children: [new PageBreak()] })
  );

  const lines = markdown.split("\n");
  let inTable = false;
  let tableRows: { cells: string[]; isHeader: boolean }[] = [];

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    const trimmed = line.trim();

    // Skip empty lines in tables
    if (inTable && (trimmed === "" || trimmed.startsWith("|---"))) {
      continue;
    }

    // Detect table rows
    if (trimmed.includes("|") && trimmed.startsWith("|")) {
      const cells = trimmed
        .split("|")
        .filter((c) => c.trim() !== "")
        .map((c) => c.trim());

      if (cells.length > 0) {
        const isHeader = !inTable;
        if (!inTable) inTable = true;
        tableRows.push({ cells, isHeader: isHeader && tableRows.length === 0 });
      }
      // Check if next line is not a table row
      if (i + 1 >= lines.length || !lines[i + 1].trim().startsWith("|")) {
        // Flush table
        elements.push(convertTableToDocx(tableRows));
        tableRows = [];
        inTable = false;
      }
      continue;
    }

    if (inTable) {
      elements.push(convertTableToDocx(tableRows));
      tableRows = [];
      inTable = false;
    }

    // Headings
    if (trimmed.startsWith("## ")) {
      elements.push(
        new Paragraph({
          heading: HeadingLevel.HEADING_2,
          spacing: { before: 400, after: 200 },
          children: [
            new TextRun({
              text: trimmed.replace(/^## /, ""),
              bold: true,
              size: 32,
              color: "1E40AF",
            }),
          ],
        })
      );
    } else if (trimmed.startsWith("### ")) {
      elements.push(
        new Paragraph({
          heading: HeadingLevel.HEADING_3,
          spacing: { before: 300, after: 150 },
          children: [
            new TextRun({
              text: trimmed.replace(/^### /, ""),
              bold: true,
              size: 26,
              color: "2563EB",
            }),
          ],
        })
      );
    } else if (trimmed.startsWith("#### ")) {
      elements.push(
        new Paragraph({
          heading: HeadingLevel.HEADING_4,
          spacing: { before: 200, after: 100 },
          children: [
            new TextRun({
              text: trimmed.replace(/^#### /, ""),
              bold: true,
              size: 24,
              color: "3B82F6",
            }),
          ],
        })
      );
    } else if (trimmed.startsWith("# ")) {
      elements.push(
        new Paragraph({
          heading: HeadingLevel.HEADING_1,
          spacing: { before: 500, after: 200 },
          border: {
            bottom: {
              color: "1E40AF",
              size: 6,
              style: BorderStyle.SINGLE,
              space: 8,
            },
          },
          children: [
            new TextRun({
              text: trimmed.replace(/^# /, ""),
              bold: true,
              size: 40,
              color: "1E40AF",
            }),
          ],
        })
      );
    }
    // Bold text (wrapped in **)
    else if (trimmed.startsWith("**") && trimmed.endsWith("**")) {
      elements.push(
        new Paragraph({
          spacing: { before: 200, after: 100 },
          children: [
            new TextRun({
              text: trimmed.replace(/\*\*/g, ""),
              bold: true,
              size: 22,
            }),
          ],
        })
      );
    }
    // List items
    else if (trimmed.startsWith("- ") || trimmed.startsWith("* ")) {
      elements.push(
        new Paragraph({
          spacing: { after: 60 },
          indent: { left: 720 },
          bullet: { level: 0 },
          children: parseInlineFormatting(trimmed.replace(/^[-*] /, "")),
        })
      );
    }
    // Numbered list
    else if (/^\d+\.\s/.test(trimmed)) {
      elements.push(
        new Paragraph({
          spacing: { after: 60 },
          indent: { left: 720 },
          children: parseInlineFormatting(trimmed.replace(/^\d+\.\s/, "")),
        })
      );
    }
    // Regular paragraph (non-empty)
    else if (trimmed !== "") {
      elements.push(
        new Paragraph({
          spacing: { after: 100 },
          children: parseInlineFormatting(trimmed),
        })
      );
    }
    // Empty line
    else {
      elements.push(new Paragraph({ spacing: { after: 60 }, children: [] }));
    }
  }

  // Flush any remaining table
  if (inTable && tableRows.length > 0) {
    elements.push(convertTableToDocx(tableRows));
  }

  return elements;
}

function parseInlineFormatting(text: string): (TextRun | ExternalHyperlink)[] {
  const runs: (TextRun | ExternalHyperlink)[] = [];

  // Also handle inline bold: **text**
  const parts: { type: "text" | "bold" | "link"; text: string; url?: string }[] = [];
  let remaining = text;

  while (remaining.length > 0) {
    // Check for bold
    const boldMatch = remaining.match(/\*\*(.+?)\*\*/);
    const linkMatch = remaining.match(/\[([^\]]+)\]\(([^)]+)\)/);

    let earliest = Infinity;
    let type: "bold" | "link" | "code" | null = null;

    if (boldMatch && boldMatch.index! < earliest) {
      earliest = boldMatch.index!;
      type = "bold";
    }
    if (linkMatch && linkMatch.index! < earliest) {
      earliest = linkMatch.index!;
      type = "link";
    }

    if (type === null) {
      // Plain text remainder
      if (remaining.trim()) {
        parts.push({ type: "text", text: remaining });
      }
      break;
    }

    // Add text before match
    if (earliest > 0) {
      parts.push({ type: "text", text: remaining.substring(0, earliest) });
    }

    if (type === "bold") {
      parts.push({ type: "bold", text: boldMatch![1] });
      remaining = remaining.substring(earliest + boldMatch![0].length);
    } else if (type === "link") {
      parts.push({ type: "link", text: linkMatch![1], url: linkMatch![2] });
      remaining = remaining.substring(earliest + linkMatch![0].length);
    }
  }

  for (const part of parts) {
    if (part.type === "bold") {
      runs.push(
        new TextRun({
          text: part.text,
          bold: true,
          size: 22,
        })
      );
    } else if (part.type === "link" && part.url) {
      runs.push(
        new ExternalHyperlink({
          children: [
            new TextRun({
              text: part.text,
              style: "Hyperlink",
              size: 22,
              color: "2563EB",
              underline: { type: "single" },
            }),
          ],
          link: part.url,
        })
      );
    } else {
      runs.push(
        new TextRun({
          text: part.text,
          size: 22,
        })
      );
    }
  }

  return runs;
}

function convertTableToDocx(
  rows: { cells: string[]; isHeader: boolean }[]
): Table {
  return new Table({
    rows: rows.map((row) => {
      const cells = row.cells.map(
        (cell) =>
          new TableCell({
            children: [
              new Paragraph({
                children: [
                  new TextRun({
                    text: cell,
                    bold: row.isHeader,
                    size: row.isHeader ? 20 : 18,
                    color: row.isHeader ? "FFFFFF" : "333333",
                  }),
                ],
                alignment: row.isHeader ? AlignmentType.CENTER : AlignmentType.LEFT,
              }),
            ],
            shading: row.isHeader
              ? { fill: "1E40AF", type: "clear", color: "1E40AF" }
              : undefined,
          })
      );
      return new TableRow({ children: cells });
    }),
  });
}
